# Generated by Django 5.0.4 on 2024-04-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(default=None)),
                ('address', models.CharField(default=None, max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
    ]
